"""init

Revision ID: 288cd25ffa4a
Revises: 
Create Date: 2022-06-01 20:52:44.049524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288cd25ffa4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marvel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_id'), 'character', ['id'], unique=False)
    op.create_index(op.f('ix_character_marvel_id'), 'character', ['marvel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_marvel_id'), table_name='character')
    op.drop_index(op.f('ix_character_id'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
