"""init

Revision ID: cb9ecff1bb51
Revises: 
Create Date: 2022-06-03 18:36:11.502105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9ecff1bb51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('marvel_id', sa.Integer(), nullable=False),
    sa.Column('comic_count', sa.Integer(), nullable=False),
    sa.Column('series_count', sa.Integer(), nullable=False),
    sa.Column('stories_count', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_created'), 'character', ['created'], unique=False)
    op.create_index(op.f('ix_character_id'), 'character', ['id'], unique=False)
    op.create_index(op.f('ix_character_marvel_id'), 'character', ['marvel_id'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=False)
    op.create_index(op.f('ix_character_updated'), 'character', ['updated'], unique=False)
    op.create_table('comic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('marvel_id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('url_detail', sa.String(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comic_created'), 'comic', ['created'], unique=False)
    op.create_index(op.f('ix_comic_id'), 'comic', ['id'], unique=False)
    op.create_index(op.f('ix_comic_marvel_id'), 'comic', ['marvel_id'], unique=False)
    op.create_index(op.f('ix_comic_updated'), 'comic', ['updated'], unique=False)
    op.create_table('character_comic',
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.id'], ),
    sa.PrimaryKeyConstraint('comic_id', 'character_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_comic')
    op.drop_index(op.f('ix_comic_updated'), table_name='comic')
    op.drop_index(op.f('ix_comic_marvel_id'), table_name='comic')
    op.drop_index(op.f('ix_comic_id'), table_name='comic')
    op.drop_index(op.f('ix_comic_created'), table_name='comic')
    op.drop_table('comic')
    op.drop_index(op.f('ix_character_updated'), table_name='character')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_marvel_id'), table_name='character')
    op.drop_index(op.f('ix_character_id'), table_name='character')
    op.drop_index(op.f('ix_character_created'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
